# -*- coding: utf-8 -*-
"""pca_tsne_umap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ta4piiLM0D_mjTBKZdkSByMF76fy-EQt
"""

# installing required libraries
# !pip install umap-learn

# importing required libraries
# from umap import UMAP
import umap.umap_ as umap
from numpy import ndarray
from pandas import DataFrame
from pandas import read_pickle
from seaborn import scatterplot
from sklearn.manifold import TSNE
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


# PCA

# defining function
def run_pca(data: DataFrame,
            feature_cols: list,
            n_components: int,
            random_state: int
            ) -> ndarray:
    # getting data from df
    features = data[feature_cols]

    # scaling data (converting values to z-scores)
    features = StandardScaler().fit_transform(features)

    # getting PCA based on given components num
    pca = PCA(n_components=n_components,
              random_state=random_state)

    # getting principal components
    principal_components = pca.fit_transform(features)

    # getting explained variation per component
    var_per_components = pca.explained_variance_ratio_
    x_var, y_var = var_per_components
    x_var_percent = round(x_var * 100, 2)
    y_var_percent = round(y_var * 100, 2)

    # getting x, y values
    x = principal_components[:, 0]
    y = principal_components[:, 1]

    # adding cols to df
    data['x'] = x
    data['y'] = y

    # defining update dict
    label_dict = {0: 'Normal',
                  1: 'Quiescent',
                  2: 'Fully senescent',
                  3: 'Senescent-like'}

    # updating labels col
    data.replace({'label': label_dict},
                 inplace=True)

    # creating plot
    scatterplot(data=data,
                x='x',
                y='y',
                hue='label')

    # defining plot axis labels
    x_label = f'PC1 ({x_var_percent}%)'
    y_label = f'PC2 ({y_var_percent}%)'

    # updating plot axis labels
    plt.xlabel(x_label)
    plt.ylabel(y_label)

    # showing plot
    plt.show()


# TSNE

# defining function
def run_tsne(data: DataFrame,
             feature_cols: list,
             n_components: int,
             perplexity: int,
             max_iter: int,
             random_state: int
             ) -> ndarray:
    # getting data from df
    features = data[feature_cols]

    # scaling data (converting values to z-scores)
    features = StandardScaler().fit_transform(features)

    # getting TSNE based on given components num
    tsne = TSNE(n_components=n_components,
                perplexity=perplexity,
                max_iter=max_iter,
                random_state=random_state)

    # getting principal components
    principal_components = tsne.fit_transform(features)

    # getting x, y values
    x = principal_components[:, 0]
    y = principal_components[:, 1]

    # adding cols to df
    data['x'] = x
    data['y'] = y

    # defining update dict
    label_dict = {0: 'Normal',
                  1: 'Quiescent',
                  2: 'Fully senescent',
                  3: 'Senescent-like'}

    # updating labels col
    data.replace({'label': label_dict},
                 inplace=True)

    # creating plot
    scatterplot(data=data,
                x='x',
                y='y',
                hue='label')

    # defining plot axis labels
    x_label = f'T-SNE 1'
    y_label = f'T-SNE 2'

    # updating plot axis labels
    plt.xlabel(x_label)
    plt.ylabel(y_label)

    # showing plot
    plt.show()

# UMAP

# defining function
def run_umap(data: DataFrame,
             feature_cols: list,
             random_state: int
             ) -> ndarray:
    # getting data from df
    features = data[feature_cols]

    # scaling data (converting values to z-scores)
    features = StandardScaler().fit_transform(features)

    # getting UMAP based on given components num
    umap_ = umap.UMAP(random_state=random_state)

    # getting principal components
    principal_components = umap_.fit_transform(features)

    # getting x, y values
    x = principal_components[:, 0]
    y = principal_components[:, 1]

    # adding cols to df
    data['x'] = x
    data['y'] = y

    # defining update dict
    label_dict = {0: 'Normal',
                  1: 'Quiescent',
                  2: 'Fully senescent',
                  3: 'Senescent-like'}

    # updating labels col
    data.replace({'label': label_dict},
                 inplace=True)

    # creating plot
    scatterplot(data=data,
                x='x',
                y='y',
                hue='label')

    # defining plot axis labels
    x_label = f'UMAP 1'
    y_label = f'UMAP 2'

    # updating plot axis labels
    plt.xlabel(x_label)
    plt.ylabel(y_label)

    # showing plot
    plt.show()


# defining main function
def main():
    """Runs main code."""
    # defining global variables
    SEED = 53
    DATA_PATH = 'D:\\UFRGS\\data\\u87\\duplo_marcada\\xgal_24_08_27\\grayscale\\treatment\\joined\\joined_tx_df_morphometry.pickle' # noqa

    # loading data
    # DATA = px.data.iris()
    DATA = read_pickle(DATA_PATH)

    # defining feature cols
    # FEATURE_COLS = ["sepal_width", "sepal_length", "petal_width", "petal_length"]
    FEATURE_COLS = ['cyto_area', 'cyto_arbox', 'cyto_radra', 'cyto_asp', 'cyto_ecc', 'cyto_rou', 'cii', 'nuc_area',
                    'nuc_arbox', 'nuc_radra', 'nuc_asp', 'nuc_ecc', 'nuc_rou', 'nii']

    # running PCA
    run_pca(data=DATA,
            feature_cols=FEATURE_COLS,
            n_components=2,
            random_state=SEED)

    # running TSNE
    run_tsne(data=DATA,
             feature_cols=FEATURE_COLS,
             n_components=2,
             perplexity=40,
             max_iter=300,
             random_state=SEED)

    # running UMAP
    run_umap(data=DATA,
             feature_cols=FEATURE_COLS,
             random_state=SEED)


######################################################################
# running main function


if __name__ == '__main__':
    main()

######################################################################
# end of current module
